### ISSUE TITLE
xz_cve-2024-3094-detect.sh - suggestion

### ISSUE THREAD

**Issue by akhepcat** [cyclone-github/scripts#1]
-  path=$(ldd "$sshd_path" 2>/dev/null | grep liblzma | awk '{print $3}' | head -n 1)

can be optimized a bit and remove an unneeded pipe:

path=$(ldd "$sshd_path" 2>/dev/null  | grep -o '/.\*liblzma[^ ]\*' | head -1)

**Comment by rugk** [comment]
You can propose PRs on GitHub and get it merged directly…
