### ISSUE TITLE
Multiple 5.6.x versions are vulnerable

### ISSUE THREAD

**Issue by nickodell** [cyclone-github/scripts#2]
This script appears to only detect 5.6.0 as vulnerable.

https://github.com/cyclone-github/scripts/blob/main/xz_cve-2024-3094-detect.sh#L48

However, versions 5.6.0 and 5.6.1 are both vulnerable.

**Comment by cyclone-github** [comment]
I'll correct this.

**Comment by ffffuuuuuuu** [comment]
a note: checking for `5.6.1-[1|2]` with this method will result in false positives for patched systems, as `xz --version` only reports the `MAJOR.MINOR.PATCH` version, i.e. 

`xz --version` would report
```
xz (XZ Utils) 5.6.1
liblzma 5.6.1
```
even on patched systems. on arch one could do `sudo pacman -Fy xz` to make sure to get
```text
core/xz 5.6.1-2 [installed]
    usr/bin/xz
```
