### ISSUE TITLE
Don't invoke xz

### ISSUE THREAD

**Issue by Firesphere** [cyclone-github/scripts#6]
This'll probably not be as easy to use as the way you're currently doing it:
`$(xz --version | head -n1 | awk '{print $4}')`
Invokes xz, to get the version.

I's probably better to not invoke xz itself, but ask the package manager. For Debian based systems, this would be:
`$(dpkg -l | grep xz | awk '{print $3}')`

**Comment by eloytoro** [comment]
+1 on this, invoking a backdoored binary is inviting the hacker into your machine

Don't execute malware, it's generally a bad idea
